#!/usr/bin/env python3
"""
sync_v8_from_js.py

Regenerates marquee_selection_instancing_v8.js from marquee_selection_instancing.js
by preserving the V8 marker header and replacing the body with the current
contents of the SpiderMonkey version.

Usage:
    python3 sync_v8_from_js.py                  # syncs in current directory
    python3 sync_v8_from_js.py /path/to/folder  # syncs in the given directory

The script only touches the V8 file. The SpiderMonkey file is the source of
truth and is never modified. If the V8 file doesn't yet have a header marker,
the script will inject one. If the V8 file is missing entirely, the script
creates it from scratch.

Exits 0 on success, 1 on error.
"""

import sys
import os
import shutil
from datetime import datetime

JS_NAME  = "marquee_selection_instancing.js"
V8_NAME  = "marquee_selection_instancing_v8.js"

# The V8 marker header. The opening and closing fence lines are matched
# verbatim, so don't change them lightly. Anything between them is the
# "V8-specific preamble" that gets preserved across syncs.
HEADER_FENCE_OPEN  = "// === V8 MARKER START — do not remove ==="
HEADER_FENCE_CLOSE = "// === V8 MARKER END — do not remove ==="

DEFAULT_HEADER = f"""{HEADER_FENCE_OPEN}
// V8 VERSION — for use with Max's `v8` object (not `js`).
//
// This file is generated by sync_v8_from_js.py from the SpiderMonkey-version
// source ({JS_NAME}). Do not edit by hand — changes here will be overwritten
// on next sync. Edit {JS_NAME} instead, then re-run the sync script.
//
// The Max API surface (JitterMatrix, JitterObject, Dict, Task, messnamed,
// post, outlet, arrayfromargs, jsarguments) works identically between the
// two engines; SpiderMonkey-specific language extensions (`for each`,
// expression closures, `with`, etc.) are not used, so the body is a
// byte-for-byte copy of the JS version.
//
// To use in a patch: replace `js {JS_NAME}` with `v8 {V8_NAME}`. All outlets,
// inlets, and message handlers stay the same.
{HEADER_FENCE_CLOSE}

"""

# Colour output when on a TTY
if sys.stdout.isatty():
    GREEN, RED, YELLOW, RESET = "\033[32m", "\033[31m", "\033[33m", "\033[0m"
else:
    GREEN = RED = YELLOW = RESET = ""

def err(msg):
    print(f"{RED}error:{RESET} {msg}", file=sys.stderr)
    sys.exit(1)

def info(msg):
    print(f"{GREEN}✓{RESET} {msg}")

def warn(msg):
    print(f"{YELLOW}!{RESET} {msg}")

def extract_existing_header(v8_text):
    """Return the V8 marker header (open fence through close fence + trailing
    blank line if present) from an existing V8 file. Returns None if no marker
    is found."""
    open_idx = v8_text.find(HEADER_FENCE_OPEN)
    if open_idx < 0:
        return None
    close_idx = v8_text.find(HEADER_FENCE_CLOSE, open_idx)
    if close_idx < 0:
        return None
    # Advance past the close fence's own newline, and consume one trailing
    # blank line if present.
    end = v8_text.find("\n", close_idx)
    if end < 0:
        end = len(v8_text)
    else:
        end += 1
        # one blank line after the marker, preserved
        if v8_text[end:end+1] == "\n":
            end += 1
    return v8_text[:end]

def main():
    base = sys.argv[1] if len(sys.argv) > 1 else "."
    js_path = os.path.join(base, JS_NAME)
    v8_path = os.path.join(base, V8_NAME)

    if not os.path.isfile(js_path):
        err(f"{JS_NAME} not found in {os.path.abspath(base)}")

    with open(js_path, "rb") as f:
        js_body = f.read()

    # Determine header: use existing V8 file's header if present, else default
    if os.path.isfile(v8_path):
        with open(v8_path, "r", encoding="utf-8") as f:
            existing_v8 = f.read()
        header = extract_existing_header(existing_v8)
        if header is None:
            warn(f"{V8_NAME} exists but has no V8 marker header; injecting default")
            header = DEFAULT_HEADER
        else:
            info(f"preserving V8 marker header from existing {V8_NAME}")
        # Backup the current V8 file before overwriting
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup = v8_path + f".bak.{ts}"
        shutil.copy2(v8_path, backup)
        info(f"backed up previous {V8_NAME} to {os.path.basename(backup)}")
    else:
        info(f"{V8_NAME} does not exist; creating with default header")
        header = DEFAULT_HEADER

    # Compose: header bytes + js body bytes
    # Header is text, body is bytes (to preserve line endings exactly).
    out = header.encode("utf-8") + js_body

    with open(v8_path, "wb") as f:
        f.write(out)

    info(f"wrote {V8_NAME} ({len(out)} bytes, {out.count(0x0a)} lines)")

    # Sanity report: confirm both files have matching post-header bodies
    with open(v8_path, "rb") as f:
        v8_text_bytes = f.read()
    v8_text = v8_text_bytes.decode("utf-8", errors="replace")
    close_idx = v8_text.find(HEADER_FENCE_CLOSE)
    body_start = v8_text.find("\n", close_idx) + 1
    # skip one trailing blank line after marker
    if v8_text[body_start:body_start+1] == "\n":
        body_start += 1
    v8_body_bytes = v8_text_bytes[len(v8_text[:body_start].encode("utf-8")):]
    if v8_body_bytes == js_body:
        info("V8 body matches JS source byte-for-byte (post-header)")
    else:
        warn("V8 body differs from JS source (post-header); check manually")
        warn(f"  js bytes: {len(js_body)}, v8 body bytes: {len(v8_body_bytes)}")

if __name__ == "__main__":
    main()